### ISSUE TITLE
Textscreens are invisible

### ISSUE THREAD

**Issue by Awesome123123** [Cherry/3D2D-TextScreens#7] opened 2015-03-26 23:00 UTC
Hello,
I am not sure if you check your comments for the text screens but I decided to write it here. All textscreens that are placed down are invisible. It would be nice if you made a patch for it.

Thanks,

Awesomenessman

**Comment by Cherry** [comment] 2015-03-27 15:41
Hello,

Thanks for the report! I'm very aware of the current issues but am out of the country at this time. I will take a look as soon as I get a spare moment.

**Comment by Dellkan** [comment] 2015-03-28 11:35
Hey guys.

Cherry/James has asked me to look into this problem in his absence.

Now, first things first, I can't actually reproduce the issue.
[![Taken today](http://cloud-4.steamusercontent.com/ugc/29611747689487071/CE0315616D0D12668816C7D6C4AB2F938CEC81F8/)](http://steamcommunity.com/sharedfiles/filedetails/?id=415275211)
(It's a screenshot taken today)

As such, I'll need your guys help to reproduce, and understand the issue to fix it.

I'll need **all** the following pieces of information. Please fill out a reply:

 - [ ] **Does the textscreen have any text at all?:** Yes/Yes, but it's tiny/No, all invisible
 - [ ] **Can you see a box/prop where the textscreens were supposed to be?:** Yes/No
 - [ ] **Does printers in DarkRP have their text?:** Yes/No
 - [ ] **Do you have any other mod with text that stopped working, or is still working?:** Yes/No (which?)
 - [ ] **Have you tried running textscreens in sandbox gamemode with absolutely no other addon?:** Yes/No
 - [ ] **Type `mat_dxlevel` in console. What does it output?:** "mat_dxlevel" = x
 - [ ] **Have you tried verifying integrity of game cache?:** Yes/No
 - [ ] **Check "Set launch options" in steam library on gmod. If you have any options in there, copy paste them here:** x

**Comment by metallicgloss** [comment] 2015-03-28 12:05
1. There is no text at all, it is invisible.
2. The invisible box is there and can be found by hovering over it with C held.
3. No errors what so ever.
4. No.
5. Other addons have stopped working. Mining System from scriptfodder not displaying them.
6. I have tried running it with no addons and in sandbox and it still doesn't show the text.
7. "mat_dxlevel" = "95" ( def. "0" )
8. Yes, and nothing had to be re-obtained. No-one on my server can see it either.
9. I have nothing there

I have also tested it in a dedicated DarkRP server hosted with SerinityServers and they still do not show up in sandbox or when the gamemode DarkRP is running. All of the other other addons that use text screens dont work there either. I hope this helps to help to get it fixed.

**Comment by Dellkan** [comment] 2015-03-28 12:20
It's a good start, thanks. 

Can you give me the server ip for one of these? I'd like to visit, see if they'll be broken for me too.

The fact that other addons has become broken for you leads me to believe that gmod itself either broke something, or messed up something. Likely, we'll find our answer in messing with either graphic settings, launch options, or some other gmod setting. Whatever fixes it for you, will likely fix it for all your broken addons (including textscreens). It also means that it is unlikely that anything can be done from textscreen's end. (I'll keep looking though, these are just initial guesses)

All that said, the comments everywhere indicates we're dealing with many different issues, so please, keep those replies coming.

**Comment by metallicgloss** [comment] 2015-03-28 12:29
Our DarkRP server that it is currently on is: 185.38.148.159:27165
and yes, since the update, your text screens and others arent working.

**Comment by FredKing27** [comment] 2015-03-28 13:03
1. No textscreens appearing
2. Box around the invisible textscreen when you press c or hit it with a phys gun
3. No errors
4. I don't use default printers so I wouldn't know however, my current printer plugin is working and it can be found here http://steamcommunity.com/sharedfiles/filedetails/?id=176802773
5. Enhanced Meth Lab from scriptfodder and drugs mod.  Meth lab has no info on the meth and drugs mod has no on screen effects
6. Yes still no text
7. mat_dxlevel = 90
8. Yes It had to get 2 files however, after it was done nothing changed same problems.
9. N/A

Gl Dellkan I rly hope yall can fix this

**Comment by Dellkan** [comment] 2015-03-28 13:47
Thank you for the report. Looking at your printer was especially illuminating.

Testing with @metallicgloss revealed some result.

I joined @metallicgloss server, and found that I too couldn't see the textscreen. After a little investigation, I found that my clientside never received the textscreen data (what the text should be, font size, font color, alpha, etc). Updating this data manually from the clientside fixed the problem.

Textscreens uses a large amount of NetworkedVariables (SetNWInt, and so forth). Apparently, the last gmod update introduced a smaller limit (32, down from 64) variables that could be active at one time on an entity. Simple guesswork, but it would appear that when that limit is reached, no data it sent or synched at all.

@FredKing27's printer works because it's using an entirely different method of communicating.

On my own test server, both I, and @metallicgloss could see both our own, and each other's textscreens just fine.


# So where does that leave us? #

 - Many addons will be affected by this, not just textscreens (and textscreens isn't responsible for that)
   - In fact, it happens **because** you have many addons installed, that each try to synch some data.
 - Textscreens must be rewritten to use a more reliable method of communication
   - Your other addons that also have issues should probably have its server/client communication rewritten too

# Don't think this is your problem? #

That could very well be. From reading the comments, it looks like we're wrestling with multiple issues. So please, post more replies following the format above.

**Comment by FredKing27** [comment] 2015-03-28 14:33
Maybe garry should undo the change it seems a bit silly of them to break a lot of addons just to change a small thing for as i see it with no reason to do so.

**Comment by metallicgloss** [comment] 2015-03-28 14:39
I would agree, but how would one contact him?

**Comment by FredKing27** [comment] 2015-03-28 15:02
idk maybe leave feedback for valve or something

**Comment by Dellkan** [comment] 2015-03-28 17:13
Reading over the changelog again (http://www.garrysmod.com/updates/), I might have misunderstood (NetworkVar got the reduced limit from 64 down to 32, not NWVars as I initially thought), which means that NWVars has a bug that prevents them from working, not a limit they've reached. There's 4-5 different ways of communicating in Garry's mod, and they all have similar names, and switch (frequently) between which is recommended for usage, and which is obsolete/deprecated. It's a somewhat frustrating terrain to cover.

Either way, I've finished rewriting a fix, which seems to work, but I won't know for sure until I have had testers confirm. See https://github.com/Dellkan/3D2D-TextScreens and give me some feedback.

**Comment by metallicgloss** [comment] 2015-03-28 18:57
I have fixed my server, if you update you server if you have it hosted. It fixes all issues.

**Comment by yahell1** [comment] 2015-03-29 07:18
Does the textscreen have any text at all?: No Just a sort invisible square where it should be
 Can you see a box/prop where the textscreens were supposed to be?: Yes
 Have there been any errors at all?: No
 Does printers in DarkRP have their text?: Yes (But im using https://scriptfodder.com/scripts/view/768)
 Do you have any other mod with text that stopped working, or is still working?: Yes (The Text on the Drug Printers seems to be frozen (https://scriptfodder.com/scripts/view/989)
 Have you tried running textscreens in sandbox gamemode with absolutely no other addon?: No
 Type mat_dxlevel in console. What does it output?: "mat_dxlevel" = "95" ( def. "0" )
 Have you tried verifying integrity of game cache?: Can't its being hosted by a provider
 Check "Set launch options" in steam library on gmod. If you have any options in there, copy paste them here: Can't its hosted online

![Proof](http://s16.postimg.org/kjsoj4v2d/rp_downtown_altered0000.jpg)

As i was spawning a textscreen i noticed this
Requesting texture value from var "$basetexture" which is not a texture value (material: gpurt)
Requesting texture value from var "$basetexture" which is not a texture value (material: gpurt)

This was in red

But then i tried again and this did not appear ^

**Comment by yahell1** [comment] 2015-03-29 07:34
I just updated and it fixed the issue.. thanks alot <3

**Comment by Swagrenade** [comment] 2015-03-29 11:04
It works fine. All I did was run the steam updater and updated to beta version of DarkRP.

**Comment by Cherry** [comment] 2015-03-31 00:25
Huge thanks to @Dellkan for taking care of this whilst I was gone.

It appears that the NWVar changes have been reverted, which inadvertently fixed the issues experienced, however I have gone ahead and merged the changes anyway, as it produces much cleaner code, and fixes a couple of outstanding issues too.

Unfortunately the change in network libraries and data storage in the recent version has resulted in all perma text screens having to be recreated. This shouldn't happen again in future, and my apologies for any inconvenience. 

Feel free to open another issue if you guys run into anything else!

**Closed by Cherry** 2015-03-31 00:25 UTC
