### ISSUE TITLE
Text Screens are not being made Permanent 

### ISSUE THREAD

**Issue by jaw20** [Cherry/3D2D-TextScreens#1] opened 2015-01-02 22:42 UTC
When we first started using textscreens we were able to make them Permanent and reload the map without having them disappear, but now every time we try to make them permanent they don't save on the map.

**Comment by Cherry** [comment] 2015-01-03 03:37
I'm unable to replicate this on a sandbox install on gm_construct in both a server and single player. Please provide more steps on how to reproduce.

**Comment by AlucardMichaelis** [comment] 2015-02-01 16:08
Hey this issue is happening to me as well, I'm not sure how it happened but if it helps at all this issue occurs with the wire textscreens for my server as well

**Comment by Cherry** [comment] 2015-02-01 16:53
Interesting observation, however I'm still unable to reproduce this on a sandbox install. I'm leaning towards a gamemode incompatibility, or possibly an admin running some cleanup commands, however without specific steps to reproduce, there isn't much I can do unfortunately.

**Comment by Cherry** [comment] 2015-02-04 20:26
@AlucardMichaelis This is almost definitely an issue with another poorly coded addon / gamemode returning something in a hook that it's not meant to. I may implement something in future to "fix" this terrible hook design in garrysmod, but currently, I'm marking this as won't-fix.

**Closed by Cherry** 2015-02-04 20:26 UTC
Labels: unable-to-replicate
